# Generated by Django 3.1.4 on 2021-02-15 06:59

from django.db import migrations, models
import scraping.models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0004_auto_20210126_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='error',
            name='data',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='url',
            name='url_data',
            field=models.JSONField(default=scraping.models.default_urls),
        ),
    ]
