# Generated by Django 3.1.4 on 2021-02-18 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0005_auto_20210215_0959'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='error',
            options={'verbose_name': 'Ошибки', 'verbose_name_plural': 'Ошибки'},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'verbose_name': 'Специализация', 'verbose_name_plural': 'Специализации'},
        ),
        migrations.AlterModelOptions(
            name='url',
            options={'verbose_name': 'Пути для скрапинга', 'verbose_name_plural': 'Пути для скрапинга'},
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Специализация'),
        ),
        migrations.AlterField(
            model_name='url',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraping.language', verbose_name='Специализация'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraping.language', verbose_name='Специализация'),
        ),
    ]
